services:
  backend:
    build: .
    command: uvicorn server:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      retries: 5
      start_period: 10s
      timeout: 10s

  frontend:
    build: .
    command: python main.py
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    restart: unless-stopped
    depends_on:
      - backend
